# Install dependencies only when needed
FROM node:16.13-alpine3.12 AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn install --network-timeout 1000000000

# Rebuild the source code only when needed
FROM node:16.13-alpine3.12
RUN apk add --no-cache mariadb-connector-c mysql-client tzdata
RUN apk add --update busybox-suid
WORKDIR /app
COPY . .
RUN chmod +x entrypoint.sh

COPY --from=deps /app/node_modules ./node_modules

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
# Uncomment the following line in case you want to disable telemetry.
ENV NEXT_TELEMETRY_DISABLED 1

EXPOSE 3000
ENTRYPOINT ["/app/entrypoint.sh"]
CMD ["yarn", "dev"]
