version: "3.3"

services:
    database:
        image: mysql:8.0.28
        volumes:
            - db_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: starter
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: test
            MYSQL_PASSWORD: test

    nextapp:
        depends_on:
            - database
        image: starter
        build: .
        restart: unless-stopped
        ports:
            - "3000:3000"

volumes:
    db_data: {}
